[project]
name = "connectOnion"
created = "2025-10-24T17:25:24.738588"
framework_version = "0.3.4"

[cli]
version = "1.0.0"
command = "co init"
template = "none"

[agent]
address = "0x2d799bf466619f7db42606764e64c09da651dd2ab142092ab7e207e617daf5c9"
short_address = "0x2d79...f5c9"
email = "0x2d799bf4@mail.openonion.ai"
email_active = true
created_at = "2025-10-24T17:25:24.738598"
algorithm = "ed25519"
default_model = "gpt-4o-mini"
max_iterations = 10
